/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Entersequence.java
 *
 * Created on Jul 15, 2013, 12:45:28 PM
 */
package bioapp;

import genelib.Searchwtmatrix;
import java.awt.ComponentOrientation;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author slim
 */
public class Entersequence extends javax.swing.JFrame {

    /**
     * Creates new form Entersequence
     */
    char[] seq;
    float[][] wtmatrix;
    int rows;
    int cols;
    ImageIcon img = new ImageIcon("images/icons/orislogo.png");

    public Entersequence(float[][] mat, int r, int c) {
        initComponents();
        this.setIconImage(img.getImage());
        this.setTitle("Enter Sequence for matrix-search");
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        wtmatrix = mat;
        rows = r;
        cols = c;
        //format textarea
        jTextAreaseq.setColumns(10);
        jTextAreaseq.setFont(new Font("Monospaced", Font.ROMAN_BASELINE, 14));
        jTextAreaseq.setLineWrap(true);
        jTextAreaseq.setWrapStyleWord(true);
        jTextAreaseq.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaseq = new javax.swing.JTextArea();
        jButtongo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldthreshhold = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldfname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter/Copy the sequence below (use Ctr+v for paste)");

        jTextAreaseq.setColumns(20);
        jTextAreaseq.setRows(5);
        jScrollPane1.setViewportView(jTextAreaseq);

        jButtongo.setText("Go");
        jButtongo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongoActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Threshhold");

        jTextFieldthreshhold.setText("0.0");

        jLabel3.setText("Enter file name to save results: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jButtongo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldthreshhold, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldfname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldthreshhold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButtongo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtongoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongoActionPerformed
        // TODO add your handling code here:
        int errorflag = 0;
        float threshold = 0;
        //copy the text area into char array
        //create a temp String with sequence
        String temp = jTextAreaseq.getText();
        //remove spaces and newlines from temp string
        while (temp.contains(" ")) {
            temp = temp.replaceFirst(" ", "");
        }
        while (temp.contains("\n")) {
            temp = temp.replaceFirst("\n", "");
        }

        // System.out.printf("new string is \n%s",temp);
        //check size seq should be more than cols
        if (temp.length() < cols) {
            errorflag = 1;
            JOptionPane.showMessageDialog(null, "Sequence length is less than positions in wt-Matrix!!!");
        }
        //check a file name is given
        if (jTextFieldfname.getText().isEmpty() && errorflag != 1) {
            errorflag = 1;
            JOptionPane.showMessageDialog(null, "Please give a file name!!!");
        }

        try {
            threshold = Float.parseFloat(jTextFieldthreshhold.getText());
        } catch (NumberFormatException e) {
            errorflag = 1;
            JOptionPane.showMessageDialog(null, "Invalid threshold!!!");
        }



        //copy sequence to char array seq
        if (errorflag == 0) {
            seq = new char[temp.length()];
            for (int i = 0; i < seq.length; i++) {
                seq[i] = temp.charAt(i);

            }
            String fname=jTextFieldfname.getText();
            //add save dir before fname
            fname = Form2.DEFAULT_SAVE_DIR + fname;
            Searchwtmatrix ob = new Searchwtmatrix(seq, wtmatrix, rows, cols, threshold, fname);
            ob.run();
        }



    }//GEN-LAST:event_jButtongoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entersequence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entersequence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entersequence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entersequence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entersequence(null, 1, 1).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtongo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaseq;
    private javax.swing.JTextField jTextFieldfname;
    private javax.swing.JTextField jTextFieldthreshhold;
    // End of variables declaration//GEN-END:variables
}
