/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bioapp;

import genelib.Readfile;
import genelib.Searchseq;
import java.awt.Color;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jnu
 */
public class Searchdnabox extends javax.swing.JFrame {

    /**
     * Creates new form Searchdnabox
     */
    //ImageIcon img = new ImageIcon(ImageIO.read(getClass().getResourceAsStream("/images/icons/orislogo.png")));
    ImageIcon img = new ImageIcon(getClass().getClassLoader().getResource("images/icons/orislogo.png"));
    
    public Searchdnabox() {
        
        initComponents();
        this.setTitle("Search Dna box");
        jTextFieldfname.setEditable(false);
        jTextFieldfname.setBackground(Color.lightGray);
        jTextFielddnabox.setEditable(false);
        jTextFielddnabox.setBackground(Color.lightGray);
        this.setIconImage(img.getImage());
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jCheckBoxsave = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldfname = new javax.swing.JTextField();
        jComboBoxdnabox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFielddnabox = new javax.swing.JTextField();
        jCheckBoxsearchmotif = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBoxsave.setText("Save results in txt file");
        jCheckBoxsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxsaveActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter File Name");

        jComboBoxdnabox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "E. Coli:TTATCCACA", "Bradyrhizobiaceca:TGTTTCACG", "Burkholderia C2:TTATGCGCA", "Burkholderia C3:TTCCCCATA", "Chlamydiae:TTTTCCACA", "Dehalococcoides:TTATCGAAA", "Flavobacteriaceae:TGTTCCACG", "Haemophilus:TTATMCACA", "Helicobacter:TCATTCACA", "Nitrobacter:TGTTTCACG", "MycoplasmaTTWTCCACA", "Prochorales:TTTTCCACA", "Synechococcus:TTTTCCACA", "Thermotoga:CCTACCACC", "Vibrio:ATGATCAAG" }));

        jLabel2.setText("Select Dna-box to search:");

        jLabel3.setText("OR");

        jTextFielddnabox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddnaboxActionPerformed(evt);
            }
        });

        jCheckBoxsearchmotif.setText("Enter your own seq");
        jCheckBoxsearchmotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxsearchmotifActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Tolerance value :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jCheckBoxsearchmotif)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxdnabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldfname, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxsave)
                            .addComponent(jTextFielddnabox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxdnabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxsearchmotif))
                    .addComponent(jTextFielddnabox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxsave)
                    .addComponent(jLabel1))
                .addGap(5, 5, 5)
                .addComponent(jTextFieldfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int saveflag = 0, errorflag = 0;
        String fname=jTextFieldfname.getText();
        //add save dir before file name
        fname=Form2.DEFAULT_SAVE_DIR+fname;
        char[] dnabox = null;
        String selected = null;
        if (jCheckBoxsearchmotif.isSelected()) {
            jTextFielddnabox.setText(jTextFielddnabox.getText().toUpperCase());
            selected = jTextFielddnabox.getText();
        } else {
            selected = jComboBoxdnabox.getSelectedItem().toString().split(":")[1];
        }
        if (selected.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter some value to search or uncheck the option");
            errorflag = 1;
        } else {
            dnabox = new char[selected.length()];
            for (int i = 0; i < selected.length(); i++) {
                dnabox[i] = selected.charAt(i);
            }
        }

        

        if (jCheckBoxsave.isSelected()) {
            saveflag = 1;
        }
        //check for a valid file name
        if (saveflag == 1) {
            fname = jTextFieldfname.getText();
            if (fname == null || fname.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Enter a valid file name");
                errorflag=1;
                

            } else {
                //add save dir before file mane
                fname = Form2.DEFAULT_SAVE_DIR + fname;
                errorflag=0;
                
            }
        }
        if (errorflag == 0) {
            //call the object to search
            Readfile ob = new Readfile();
            String tolerance=jComboBox1.getSelectedItem().toString();
            Searchseq ob2 = new Searchseq(ob.returnseq(), dnabox, Integer.parseInt(tolerance), 1, 1, saveflag, fname,false);
            ob2.start();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBoxsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxsaveActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxsave.isSelected()) {
            jTextFieldfname.setEditable(true);
            jTextFieldfname.setBackground(Color.white);
        } else {
            jTextFieldfname.setEditable(false);
            jTextFieldfname.setBackground(Color.lightGray);
        }
    }//GEN-LAST:event_jCheckBoxsaveActionPerformed

    private void jCheckBoxsearchmotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxsearchmotifActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxsearchmotif.isSelected()) {
            jTextFielddnabox.setEditable(true);
            jTextFielddnabox.setBackground(Color.white);
        } else {
            jTextFielddnabox.setEditable(false);
            jTextFielddnabox.setBackground(Color.lightGray);
        }
    }//GEN-LAST:event_jCheckBoxsearchmotifActionPerformed

    private void jTextFielddnaboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddnaboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddnaboxActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    }
        // TODO add your handling code here:}//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Searchdnabox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Searchdnabox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Searchdnabox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Searchdnabox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Searchdnabox().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxsave;
    private javax.swing.JCheckBox jCheckBoxsearchmotif;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxdnabox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFielddnabox;
    private javax.swing.JTextField jTextFieldfname;
    // End of variables declaration//GEN-END:variables
}
