/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Settingsform.java
 *
 * Created on Apr 21, 2013, 11:09:28 PM
 */
package bioapp;

import static bioapp.Form2.getjarPath;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.URL;
import java.net.URLDecoder;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author slim
 */
public class Settingsform extends javax.swing.JFrame {

    ImageIcon img = new ImageIcon("images/icons/orislogo.png");

    /**
     * Creates new form Settingsform
     */
    public Settingsform() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Settings");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setIconImage(img.getImage());
        jTextFieldopendirectory.setText(Form2.DEFAULT_OPEN_DIR);
        jTextFieldincreament.setText(Form2.DEFAULT_INCREAMENT);
        jTextFieldwinsize.setText(Form2.DEFAULT_WIN_SIZE);
        jTextFieldsavedir.setText(Form2.DEFAULT_SAVE_DIR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public boolean isInt(String s) {
        try {
            Integer.parseInt(s);
        } catch (NumberFormatException e) {
            return false;
        }
        // if we didn't return false
        return true;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldwinsize = new javax.swing.JTextField();
        jTextFieldincreament = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxpriority = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldopendirectory = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonchooseopendir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldsavedir = new javax.swing.JTextField();
        jButtonchoosesavedir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Change Settings");

        jLabel2.setText("Enter Default Window size:");

        jLabel3.setText("Enter Default Increament size:");

        jTextFieldwinsize.setText("50000");

        jTextFieldincreament.setText("10000");

        jLabel4.setText("Select App Priority(No restart reqd) :");

        jComboBoxpriority.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "High", "Medium", "Low" }));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("*High priority will utilize max CPU cores and perform Faster");

        jLabel6.setText("Enter Default Open Directory:");

        jLabel7.setText("Restart Application for Settings to take Effect");

        jButtonchooseopendir.setText("Choose");
        jButtonchooseopendir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonchooseopendirActionPerformed(evt);
            }
        });

        jLabel8.setText("Enter Default Save Directory:");

        jButtonchoosesavedir.setText("Choose");
        jButtonchoosesavedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonchoosesavedirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxpriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldincreament)
                            .addComponent(jTextFieldwinsize, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jTextFieldopendirectory)
                            .addComponent(jTextFieldsavedir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonchooseopendir)
                            .addComponent(jButtonchoosesavedir))))
                .addGap(0, 137, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldwinsize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldincreament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldopendirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonchooseopendir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxpriority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldsavedir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jButtonchoosesavedir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldincreament, jTextFieldwinsize});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String winsize;
        String inc, opendir, savedir;
        int priority;
        int errorflag = 0;
        //check all values are entered
        if (jTextFieldincreament.getText().isEmpty() || jTextFieldwinsize.getText().isEmpty()) {
            errorflag = 1;
            JOptionPane.showMessageDialog(null, "Please check the values");
        } //check if only integers are entered for winsize and increament
        else if (!isInt(jTextFieldincreament.getText())) {
            errorflag = 1;
            JOptionPane.showMessageDialog(null, "Please enter integer value for increament");
        } else if (!isInt(jTextFieldwinsize.getText())) {
            errorflag = 1;
            JOptionPane.showMessageDialog(null, "Please enter integer value for window size");
        }

        if (errorflag == 0) {

            winsize = jTextFieldwinsize.getText();
            inc = jTextFieldincreament.getText();
            opendir = jTextFieldopendirectory.getText();
            savedir = jTextFieldsavedir.getText();
            priority = jComboBoxpriority.getSelectedIndex();
            System.out.println("prority=" + priority + "winsize=" + winsize + "inccr" + inc);

            //write new settings.cfg file
            String path = null;
            try {
                path = getjarPath();
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(Settingsform.class.getName()).log(Level.SEVERE, null, ex);
            }
            String fileSeparator = System.getProperty("file.separator");
            String newDir = path + fileSeparator;

            //write to same directory as oris
            File f = new File(path + "/settings.cfg");
            BufferedWriter writer = null;
            try {
                writer = new BufferedWriter(new FileWriter(f));
                writer.write("DEAFULT_WIN_SIZE\t" + winsize);
                writer.newLine();
                writer.write("DEAFULT_INCREAMENT\t" + inc);
                writer.newLine();
                //update the values in the program
                Form2.DEFAULT_WIN_SIZE = winsize;
                Form2.DEFAULT_INCREAMENT = inc;
                if (priority == 0) {
                    writer.write("PRIORITY\tH");
                    Form2.PRIORITY = 'H';
                } else if (priority == 1) {
                    writer.write("PRIORITY\tM");
                    Form2.PRIORITY = 'M';
                } else if (priority == 2) {
                    writer.write("PRIORITY\tL");
                    Form2.PRIORITY = 'L';
                }
                writer.newLine();
                writer.write("DEAFULT_SAVE_DIRECTORY\t" + savedir);
                writer.newLine();
                writer.write("DEAFULT_OPEN_DIRECTORY\t" + opendir);
                writer.close();
            } catch (IOException ex) {
                Logger.getLogger(Settingsform.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(null, "Settings Saved. Please restart Oris for settings to take effect");


            this.dispose();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonchooseopendirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonchooseopendirActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();

        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            jTextFieldopendirectory.setText(chooser.getSelectedFile().toString() + "/");
        } else {
        }
    }//GEN-LAST:event_jButtonchooseopendirActionPerformed

    private void jButtonchoosesavedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonchoosesavedirActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();

        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            jTextFieldsavedir.setText(chooser.getSelectedFile().toString() + "/");
        } else {
        }
    }//GEN-LAST:event_jButtonchoosesavedirActionPerformed
 //function to get path of ORIS
    public static String getjarPath() throws UnsupportedEncodingException {
        URL url = Form2.class.getProtectionDomain().getCodeSource().getLocation();
        String jarpath = URLDecoder.decode(url.getFile(), "UTF-8");
        String parentpath = new File(jarpath).getParentFile().getPath();
        return parentpath;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settingsform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settingsform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settingsform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settingsform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settingsform().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonchooseopendir;
    private javax.swing.JButton jButtonchoosesavedir;
    private javax.swing.JComboBox jComboBoxpriority;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldincreament;
    private javax.swing.JTextField jTextFieldopendirectory;
    private javax.swing.JTextField jTextFieldsavedir;
    private javax.swing.JTextField jTextFieldwinsize;
    // End of variables declaration//GEN-END:variables
}
