/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Trimerbendindform.java
 *
 * Created on Apr 4, 2013, 5:19:05 PM
 */
package bioapp;

import genelib.Readfile;
import genelib.Trimermethod;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author slim
 */
public class Trimerbendindform extends javax.swing.JFrame {

    ImageIcon img = new ImageIcon("images/icons/orislogo.png");

    /** Creates new form Trimerbendindform */
    public Trimerbendindform() {
        initComponents();
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jTextFieldfname.setEditable(false);
        jTextFieldfname.setBackground(Color.lightGray);
        this.setIconImage(img.getImage());
        this.setTitle("Select Parameters for DNA Bending Analysis");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelstart = new javax.swing.JLabel();
        jTextFieldoristart = new javax.swing.JTextField();
        jLabelend = new javax.swing.JLabel();
        jTextFieldoriend = new javax.swing.JTextField();
        jButtongo = new javax.swing.JButton();
        jCheckBoxsavefile = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldfname = new javax.swing.JTextField();
        jTextFieldwinsize = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldorisite = new javax.swing.JTextField();
        jCheckBoxoptioncenter = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldinc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelstart.setText("Enter the origin site interval(default)");

        jLabelend.setText("To");

        jButtongo.setText("Go");
        jButtongo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongoActionPerformed(evt);
            }
        });

        jCheckBoxsavefile.setText("Save plot data as txt file");
        jCheckBoxsavefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxsavefileActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter File Name");

        jTextFieldfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldfnameActionPerformed(evt);
            }
        });

        jTextFieldwinsize.setText("100");

        jLabel2.setText("Enter Window size: ");

        jLabel3.setText("Or");

        jCheckBoxoptioncenter.setText("Enter the center of origin site");

        jLabel4.setText("Enter Increment");

        jTextFieldinc.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(217, 217, 217))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(200, 200, 200)
                                    .addComponent(jButtongo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(106, 106, 106)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addComponent(jTextFieldoristart, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(36, 36, 36)
                                            .addComponent(jLabelend)))))
                            .addGap(3, 3, 3))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBoxoptioncenter)
                                .addComponent(jLabelstart))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldorisite, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldoriend, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxsavefile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldfname, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldinc, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldwinsize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldoriend, jTextFieldoristart});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelstart)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldoristart, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldoriend, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelend))
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldorisite, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxoptioncenter))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldwinsize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jCheckBoxsavefile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldfname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jButtongo)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldinc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldfname, jTextFieldoriend, jTextFieldorisite, jTextFieldoristart, jTextFieldwinsize});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxsavefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxsavefileActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxsavefile.isSelected()) {
            jTextFieldfname.setEditable(true);
            jTextFieldfname.setBackground(Color.WHITE);
        } else {

            jTextFieldfname.setEditable(false);
            jTextFieldfname.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_jCheckBoxsavefileActionPerformed

    private void jButtongoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongoActionPerformed
        // TODO add your handling code here:

        String fname = null;
        int winsize = 0;
        int inc=1;
        int saveflag = 0, flag = 1;
        int oristart = 0, oriend = 0;

        try {
            if (jCheckBoxoptioncenter.isSelected()) {
                oristart = Integer.parseInt(jTextFieldorisite.getText()) - 500;
                oriend = Integer.parseInt(jTextFieldorisite.getText()) + 500;
            } else {
                oristart = Integer.parseInt(jTextFieldoristart.getText());
                oriend = Integer.parseInt(jTextFieldoriend.getText());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please check the values");
            flag = 0;
            e.printStackTrace();

        }

        if (jCheckBoxsavefile.isSelected() && flag == 1) {
            saveflag = 1;
        }
         
            if (saveflag == 1) {
                fname = jTextFieldfname.getText();
                if (fname == null || fname.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Enter a valid file name");
                    flag=0;

                } else {
                    //add save dir before file mane
                    fname = Form2.DEFAULT_SAVE_DIR + fname;
                    flag=1;
                }
            }
        

        if (oriend <= oristart && flag == 1) {

            JOptionPane.showMessageDialog(null, "Please check the values");
            flag = 0;
        }

        if (oristart < 0 && flag == 1) {

            JOptionPane.showMessageDialog(null, "Start value < 0, Please check the values");
            flag = 0;
        }

        try {
            winsize = Integer.parseInt(jTextFieldwinsize.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please check the Window size");
            flag = 0;
            e.printStackTrace();

        }
        try {
           inc = Integer.parseInt(jTextFieldinc.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please check the Window size");
            flag = 0;
            e.printStackTrace();

        }

        //define winsize >=3 as no trimers for winsize<3
        if (winsize < 3 && flag == 1) {

            JOptionPane.showMessageDialog(null, "Window size can not be < 3, Please check the values");
            flag = 0;
        }
        if (winsize > oriend-oristart+1 && flag == 1) {

            JOptionPane.showMessageDialog(null, "Window size can not be more than length of origin,Please check the values");
            flag = 0;
        }

        if (flag == 1) {
            Readfile ob = new Readfile();
            //add save dir before fname
            
            Trimermethod ob2 = new Trimermethod(ob.returnseq(), winsize,inc, oristart, oriend, saveflag, fname);
            ob2.start();
        }
    }//GEN-LAST:event_jButtongoActionPerformed

    private void jTextFieldfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldfnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trimerbendindform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trimerbendindform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trimerbendindform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trimerbendindform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Trimerbendindform().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtongo;
    private javax.swing.JCheckBox jCheckBoxoptioncenter;
    private javax.swing.JCheckBox jCheckBoxsavefile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelend;
    private javax.swing.JLabel jLabelstart;
    private javax.swing.JTextField jTextFieldfname;
    private javax.swing.JTextField jTextFieldinc;
    private javax.swing.JTextField jTextFieldoriend;
    private javax.swing.JTextField jTextFieldorisite;
    private javax.swing.JTextField jTextFieldoristart;
    private javax.swing.JTextField jTextFieldwinsize;
    // End of variables declaration//GEN-END:variables
}
