/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Wholecorr.java
 *
 * Created on Apr 3, 2013, 9:42:38 PM
 */
package bioapp;

//import genelib.Correlation;
import genelib.Correlationwholegenome;
import genelib.Readfile;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author slim
 */
public class Wholecorr extends javax.swing.JFrame {

    /**
     * Creates new form Wholecorr
     */
    ImageIcon img = new ImageIcon(getClass().getClassLoader().getResource("images/icons/orislogo.png"));

    public Wholecorr() {
        initComponents();
        this.setIconImage(img.getImage());
        this.setTitle("Correlation for Whole Genome");
        this.setResizable(false);
        jTextFieldfname.setEditable(false);
        jTextFieldfname.setBackground(Color.lightGray);
        this.setTitle("Enter parameters for Correlation for whole genome");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelfname = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldfname = new javax.swing.JTextField();
        jCheckBoxsave = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldkmax = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldkmultiple = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelfname.setText("Enter File Name");

        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBoxsave.setText("Save Plot Data in text file");
        jCheckBoxsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxsaveActionPerformed(evt);
            }
        });

        jLabel1.setText("Correlation for Whole Genome (This may take a long time)");

        jLabel2.setText("Enter max k value");

        jLabel4.setText("Choose a value for k to a multiple of");

        jTextFieldkmultiple.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addComponent(jLabelfname, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldfname, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldkmultiple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldkmax, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBoxsave)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabelfname});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldkmax, jTextFieldkmultiple});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldkmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldkmultiple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jCheckBoxsave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldfname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelfname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addGap(47, 47, 47))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabelfname});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxsaveActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxsave.isSelected()) {
            jTextFieldfname.setEditable(true);
            jTextFieldfname.setBackground(Color.white);
        } else {
            jTextFieldfname.setEditable(false);
            jTextFieldfname.setBackground(Color.lightGray);
        }

    }//GEN-LAST:event_jCheckBoxsaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int winsize = 0, inc = 0, kval = 0, multipleval = 1;
        int errorflag = 0;
        int saveflag = 0;
        String fname = null;
        Readfile ob = new Readfile();
        winsize = Integer.parseInt(ob.returnglength());


        if (jTextFieldkmax.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a k value");
            errorflag = 1;
        } else {
            kval = Integer.parseInt(jTextFieldkmax.getText());
        }


        if (kval > winsize - 1) {
            JOptionPane.showMessageDialog(null, "k cannot exceed total_genome_size-1");
            errorflag = 1;
        }
        if (errorflag == 0) {
            kval = Integer.parseInt(jTextFieldkmax.getText());
            if (kval <= 0) {
                JOptionPane.showMessageDialog(null, "Please enter k more than 0");
                errorflag = 1;
            }
        }

        if (jTextFieldkmultiple.getText().equals("")) {
            jTextFieldkmultiple.setText(String.valueOf(1));
        }
        multipleval = Integer.parseInt(jTextFieldkmultiple.getText());

        if (multipleval <= 0) {
            JOptionPane.showMessageDialog(null, "Please enter value more than 0");
            errorflag = 1;
        }



        if (jCheckBoxsave.isSelected()) {
            saveflag = 1;

        }
        //check for a valid file name
        if (saveflag == 1) {
            fname = jTextFieldfname.getText();
            if (fname == null || fname.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Enter a valid file name");
                errorflag = 1;


            } else {
                //add save dir before file mane
                fname = Form2.DEFAULT_SAVE_DIR + fname;
                errorflag = 0;

            }
        }



        if (errorflag == 0) {


            //winsize=winsize-1;
            //kval=winsize;
            inc = 1;
            Correlationwholegenome ob2 = new Correlationwholegenome(ob.returnseq(), winsize, inc, kval, multipleval, saveflag, fname);
            ob2.start();
            // this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wholecorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wholecorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wholecorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wholecorr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wholecorr().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelfname;
    private javax.swing.JTextField jTextFieldfname;
    private javax.swing.JTextField jTextFieldkmax;
    private javax.swing.JTextField jTextFieldkmultiple;
    // End of variables declaration//GEN-END:variables
}
